---
# vars file for squid
_squid_requirements:
  default: []
  Archlinux:
    - libxml2

squid_requirements: "{{ _squid_requirements[ansible_distribution] | default(_squid_requirements['default']) }}"

squid_packages:
  - squid

squid_user: squid

squid_group: squid

_squid_config_directory:
  default: /etc/squid

squid_config_directory: "{{ _squid_config_directory[ansible_distribution] | default(_squid_config_directory['default']) }}"

squid_config_file: squid.conf

_squid_service:
  default: squid

squid_service: "{{ _squid_service[ansible_distribution] | default(_squid_service['default']) }}"
