---
- name: Set Squid Server
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    # squid_port: 3133 default: 3128
    squid_user: lczupryn
    squid_pass: Lczupryn123!
  roles:
    - robertdebock.squid
    - lczupryn.basicauth
